options:
  hosts:
    type: string
    default: ""
    description: |
        A comma-separated list of domain names that point to your API. 
        For example: example.com. At least one of hosts, uris, or methods 
        should be specified.
  uris:
    type: string
    default: ""
    description: |
        A comma-separated list of URIs prefixes that point to your API. 
        For example: /my-path. At least one of hosts, uris, or methods 
        should be specified.
  methods:
    type: string
    default: ""
    description: |
        A comma-separated list of HTTP methods that point to your API. For 
        example: GET,POST. At least one of hosts, uris, or methods should 
        be specified.
